spring:
  session:
      store-type: none
  datasource:
    url: jdbc:mysql://39.107.78.95:3306/jialong?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  resources:
   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${img.location}

  mvc:
    static-path-pattern: /**
img:
  location: D:/image/test/
  #location: /usr/local/apache-tomcat-8.5.27/webapps/image/

imgurl:
  url: http://localhost:8888/
  #url: http://39.107.78.95:8888/jlmanager/

mybatis:
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocations: classpath:mybatis/mybatis-config.xml
    typeAliasesPackage: com.jialong.jlmanager.model
    configuration:
      map-underscore-to-camel-case: true






