spring:
  session:
      store-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/jialong?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapperLocations: classpath:mybatis/mapper/*.xml
    configLocations: classpath:mybatis/mybatis-config.xml
    typeAliasesPackage: com.jialong.jlmanager.model
    configuration:
      map-underscore-to-camel-case: true

